# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test',
                'doc_host': 'https://noxikoxi.github.io',
                'git_url': 'https://github.com/noxikoxi/nbdev_test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.core': { 'nbdev_test.core.HelloSayer': ('core.html#hellosayer', 'nbdev_test/core.py'),
                                 'nbdev_test.core.HelloSayer.__init__': ('core.html#hellosayer.__init__', 'nbdev_test/core.py'),
                                 'nbdev_test.core.HelloSayer.say': ('core.html#hellosayer.say', 'nbdev_test/core.py'),
                                 'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py'),
                                 'nbdev_test.core.say_goodbye': ('core.html#say_goodbye', 'nbdev_test/core.py'),
                                 'nbdev_test.core.say_hello': ('core.html#say_hello', 'nbdev_test/core.py')}}}
